### ISSUE TITLE
Elder Fruit

### ISSUE THREAD

**Issue by NiceHairs** [MysticMods/Druidcraft#140] opened 2021-10-15 15:17 UTC
### General Information

**Describe the bug:**
Elder Fruits don't have a texture/model and appear as a violet-black cube.

**To Reproduce:**

1. Place Sapling or find a tree
2. Watch Elderfruit grow

**Expected behavior:**
Elderfruit with texture

***

### Environment Versions
1.16.5

**Mystic Mods Versions**
- Druidcraft-1.16.5-0.4.53

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 36.2.4
- Minecraft: 1.16.5
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
![Screenshot_25](https://user-images.githubusercontent.com/42701554/137511541-7fc07d41-6160-44ec-ab56-0dea01a7130a.png)

**Comment by VulpTheKangaFox** [comment] 2021-10-15 15:37
Closing because it's a duplicate of issue #136

**Closed as completed by VulpTheKangaFox** 2021-10-15 15:37 UTC
