### ISSUE TITLE
GUI for the 2x crate and the 4x crate are wonky (not the scale issue)

### ISSUE THREAD

**Issue by ZeroLevels** [MysticMods/Druidcraft#115] opened 2021-05-02 20:36 UTC
### General Information
**Describe the bug:**
1. **2x crate** has the "Inventory" title stuck right in the bottom row of the player inventory.
2. **4x crate**'s _player inventory_ is shifted by 1 pixel to the right.

**To Reproduce:**
1. Place down either the 1x2 sized crate, or the 2x2 sized crate
2. Open their GUIs

***

**Mystic Mods Versions**
Druidcraft (v0.4.52) for MC 1.16.5

***

### Logging Information
No crash.

***

### Additional Information
**Screenshots (if available):**
![image](https://user-images.githubusercontent.com/3106890/116826868-405f5180-ab64-11eb-943c-d8309c48f090.png)
![image](https://user-images.githubusercontent.com/3106890/116826856-27ef3700-ab64-11eb-9979-56d2e7951f0e.png)

**Comment by Brun333rp** [comment] 2021-05-04 22:16
this issue is duplicate of #90

**Comment by noobanidus** [comment] 2021-05-05 00:24
Indeed a duplicate of #90, thanks for pointing it out.

**Closed by noobanidus** 2021-05-05 00:24 UTC
