### ISSUE TITLE
Option to disable tree/plant worldgen

### ISSUE THREAD

**Issue by Mike-U5** [MysticMods/Druidcraft#117] opened 2021-05-08 16:25 UTC
It's currently possible to control mob spawns and ore spawns, but not tree/plant spawns. It'd be nice if this was possible.

**Comment by Brun333rp** [comment] 2021-05-09 00:32
duplicate of #102

**Comment by Mike-U5** [comment] 2021-05-09 14:19
I also meant things like Blueberry bushes, but I agree that it's close enough.

**Closed** 2021-05-09 14:20 UTC
